---
title: "Red-list African elephant dynamics"
author: "Charles T T Edwards (Wellington, New Zealand)"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: no
vignette: >
  %\VignetteIndexEntry{red}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path = 'fig/red-', fig.width = 6, tidy = TRUE, tidy.opts = list(blank = TRUE, width.cutoff = 95), message = FALSE, warning = FALSE, collapse = TRUE, comment = "#>")

options(rmarkdown.html_vignette.check_title = FALSE)

suppressPackageStartupMessages(library(rstan))
suppressPackageStartupMessages(library(rstudioapi))
options(mc.cores = parallel::detectCores())
```

```{r}
library(red)

reg_ll <- stan_model(model_code = model_code("slope"), model_name = "log-linear")
reg_lp <- stan_model(model_code = model_code("poly"),  model_name = "log-polynomial")
```

# Forest

```{r}
data(forest)
```

## Log-linear model fit
```{r}
# get initial values
ini <- with(reg_dat, list(x0_log = rep(-1, sum(S)), 
            alpha0 = 0,
            alphaC = rep(0, C),
            alphaS = rep(0, sum(S)),
            sigma = 1, tau = c(0.1,0.1)))

reg_map <- optimizing(reg_ll, reg_dat, init = function() ini, as_vector = FALSE)

reg_ini         <- list()
reg_ini$x0_log  <- reg_map$pars$x0_log
reg_ini$alpha0  <- reg_map$pars$alpha0
reg_ini$alphaC  <- reg_map$pars$alphaC
reg_ini$alphaS  <- reg_map$pars$alphaS
reg_ini$sigma   <- 1
reg_ini$tau     <- c(0.1,0.1)
```

```{r, results = 'hide'}
# MCMC sampling
reg_ll_out <- sampling(reg_ll, data = reg_dat, init = function() reg_ini, chains = 2) 
```

```{r, echo = FALSE}
gg <- traceplot(reg_ll_out, pars = c("parameter_summary", "error_summary", "output_summary"))
gg <- gg + facet_wrap(~parameter, scales = "free_y") + theme_bw(base_size = 12) + guides(col = FALSE)
gg <- gg + ggtitle("Trace summary statistics")
print(gg)
```

```{r, echo = FALSE}
dat$density_sim <- posterior(reg_ll_out, "y_sim", fun = "median")[[1]]

gg <- ggplot(dat) + 
    geom_point(aes(x = density, y = density_sim)) + 
    facet_wrap(~country) +
    labs(x = "Observed", y = "Predicted") + 
    geom_abline(intercept = 0, slope = 1) +
    theme_bw(base_size = 14) +
    scale_y_log10() + scale_x_log10() +
    ggtitle("Posterior prediction of survey density data")
print(gg)
```

## Log-polynomial model fit
```{r}
# get initial values
ini <- with(reg_dat, list(x0_log = rep(-1, sum(S)), 
            alpha0 = 0,
            alphaC = rep(0, C),
            alphaS = rep(0, sum(S)),
            beta0 = 0,
            betaC = rep(0, C),
            betaS = rep(0, sum(S)),
            sigma = 1, tau = c(0.1,0.1,0.1,0.1)))

reg_map <- optimizing(reg_lp, reg_dat, init = function() ini, as_vector = FALSE)

reg_ini         <- list()
reg_ini$x0_log  <- reg_map$pars$x0_log
reg_ini$alpha0  <- reg_map$pars$alpha0
reg_ini$alphaC  <- reg_map$pars$alphaC
reg_ini$alphaS  <- reg_map$pars$alphaS
reg_ini$beta0   <- reg_map$pars$beta0
reg_ini$betaC   <- reg_map$pars$betaC
reg_ini$betaS   <- reg_map$pars$betaS
reg_ini$sigma   <- 1
reg_ini$tau     <- c(0.1,0.1,0.1,0.1)
```

```{r, results = 'hide'}
# MCMC sampling
reg_lp_out <- sampling(reg_lp, data = reg_dat, init = function() reg_ini, chains = 2) 
```

```{r, echo = FALSE}
gg <- traceplot(reg_lp_out, pars = c("parameter_summary", "error_summary", "output_summary"))
gg <- gg + facet_wrap(~parameter, scales = "free_y") + theme_bw(base_size = 12) + guides(col = FALSE)
gg <- gg + ggtitle("Trace summary statistics")
print(gg)
```

```{r, echo = FALSE}
dat$density_sim <- posterior(reg_lp_out, "y_sim", fun = "median")[[1]]

gg <- ggplot(dat) + 
    geom_point(aes(x = density, y = density_sim)) + 
    facet_wrap(~country) +
    labs(x = "Observed", y = "Predicted") + 
    geom_abline(intercept = 0, slope = 1) +
    theme_bw(base_size = 14) +
    scale_y_log10() + scale_x_log10() +
    ggtitle("Posterior prediction of survey density data")
print(gg)
```






