---
title: "Data preparation for Red List Assessment"
author: "Charles T T Edwards (Wellington, New Zealand)"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: no
vignette: >
  %\VignetteIndexEntry{inputsRedList}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 6, tidy = TRUE, tidy.opts = list(blank = TRUE, width.cutoff = 95), message = FALSE, warning = FALSE, collapse = TRUE, comment = "#>")
options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r}
library(plyr)
library(redData)
```

# Preliminaries

Load data and subset:
```{r}
data(AED)

dat_global <- AED[, c('region', 'country', 'year', 'zone', 'estimate', 'survey_area', 'modal_survey_area', 'density', 'n_surveys', 'delete')]

# only use data up to 2015
dat_global <- subset(dat_global, year < 2016)
```

Delete surveys with extreme area sizes:
```{r}
dat_global$density[dat_global$delete] <- NA
dat_global <- subset(dat_global, !is.na(density))
```

# Forest
```{r}
dat <- subset(dat_global, region == 'forest')

# Start of model
year_start <- 1974

# Start of decline
year_N0    <- 1984
```

```{r, echo = FALSE}
# for some reason this site doesn't work
dat <- subset(dat, zone != "MPD area")
```

```{r}
# year labels for plotting
dat$year_label <- dat$year

# year = 1 corresponds to start year
dat$year <- dat$year - year_start + 1

stopifnot(all(dat$year >= 1))

# year covariate
years       <- 1:max(dat$year)
year_labels <- year_start:max(dat$year_label)

stopifnot(length(years) == length(year_labels))

# start year
start <- as.integer(match(year_N0, year_labels))

# zones for each country
number_zones_per_country <- apply(with(dat, table(country, zone) > 0), 1, sum)

zones_per_country <- dlply(dat, .(country), summarize, zones = as.character(unique(zone)))
zones_per_country <- lapply(zones_per_country, function(x) x[,1])

stopifnot(all(names(zones_per_country) == names(number_zones_per_country)))
stopifnot(all(number_zones_per_country == unlist(lapply(zones_per_country, length))))

# order data by country then zone
dat <- dat[order(dat$country, dat$zone),]

# extract vector of countries
countries <- names(zones_per_country)

# check that order of zones in 'zones_per_country' matches
# the ordering of the zones in 'dat'
for (i in countries) {
    
    tmp <- subset(dat, country == i)
    
    stopifnot(all(unique(tmp$zone) == zones_per_country[[i]]))
    stopifnot(length(unique(tmp$zone)) == number_zones_per_country[i])
}

# extract ordered vector of zones
zones <- as.character(unlist(zones_per_country))

# dimensions
N <- nrow(dat)
Y <- max(years)
S <- as.integer(number_zones_per_country)
C <- length(countries)

stopifnot(length(S) == C)
stopifnot(sum(S) == length(zones))

# look-up vectors for survey data
X   <- list()
X$Y <- match(dat$year, years)
X$S <- match(dat$zone, zones)
X$C <- match(dat$country, countries)

# check numbers match
stopifnot(all(table(X$C) == table(dat$country)))

# check again
for (i in 1:nrow(dat)) {
    
    stopifnot(dat$country[i] == countries[X$C[i]])
    stopifnot(dat$zone[i]    == zones[X$S[i]])
}

# check
stopifnot(all.equal(dat$year, years[X$Y]))
stopifnot(all.equal(dat$zone, zones[X$S]))
stopifnot(all.equal(dat$country, countries[X$C]))

# make area sizes
areas <- merge(expand.grid(year = years, zone = zones), dat[, c('year', 'zone', 'survey_area')], all = TRUE)
areas <- reshape2::acast(areas, year~zone, fun.aggregate = function(x) mean(x, na.rm = TRUE), value.var = 'survey_area', fill = as.numeric(NA), drop = FALSE)

areas <- apply(areas, 2, redData::fill, complete = TRUE)

stopifnot(all(colnames(areas) == zones))

# get modal areas per zone
modal_areas <- data.frame(zone = dat$zone, modal_survey_area = dat$modal_survey_area)[!duplicated(data.frame(dat$zone, dat$modal_survey_area)),]
stopifnot(all(modal_areas$zone == zones))
stopifnot(nrow(modal_areas) == sum(S))

modal_areas$max_modal_survey_area <- numeric(sum(S))
for (i in 1:sum(S)) {
    modal_areas$max_modal_survey_area[i] <- max(as.numeric(unlist(strsplit(as.character(modal_areas[i,2]), ";"))))
}
```

```{r}
# save regression input data
forest <- list(N = N, Y = Y, S = S, C = C, XY = X$Y, XC = X$C, XS = X$S,
                y = dat$density, 
                start = start,
                survey_area = t(areas), 
                range_area = modal_areas$max_modal_survey_area,
                use_relative_survey_area = FALSE)
                
save(forest, dat, file = "../data/forest.rda")
```

# Savannah
```{r}
dat <- subset(dat_global, region == 'savannah')

# Start of model
year_start <- 1963

# Start of decline
year_N0    <- 1965
```

```{r}
# year labels for plotting
dat$year_label <- dat$year

# year = 1 corresponds to start year
dat$year <- dat$year - year_start + 1

stopifnot(all(dat$year >= 1))

# year covariate
years       <- 1:max(dat$year)
year_labels <- year_start:max(dat$year_label)

stopifnot(length(years) == length(year_labels))

# start year
start <- as.integer(match(year_N0, year_labels))

# zones for each country
number_zones_per_country <- apply(with(dat, table(country, zone) > 0), 1, sum)

zones_per_country <- dlply(dat, .(country), summarize, zones = as.character(unique(zone)))
zones_per_country <- lapply(zones_per_country, function(x) x[,1])

stopifnot(all(names(zones_per_country) == names(number_zones_per_country)))
stopifnot(all(number_zones_per_country == unlist(lapply(zones_per_country, length))))

# order data by country then zone
dat <- dat[order(dat$country, dat$zone),]

# extract vector of countries
countries <- names(zones_per_country)

# check that order of zones in 'zones_per_country' matches
# the ordering of the zones in 'dat'
for (i in countries) {
    
    tmp <- subset(dat, country == i)
    
    stopifnot(all(unique(tmp$zone) == zones_per_country[[i]]))
    stopifnot(length(unique(tmp$zone)) == number_zones_per_country[i])
}

# extract ordered vector of zones
zones <- as.character(unlist(zones_per_country))

# dimensions
N <- nrow(dat)
Y <- max(years)
S <- as.integer(number_zones_per_country)
C <- length(countries)

stopifnot(length(S) == C)
stopifnot(sum(S) == length(zones))

# look-up vectors for survey data
X   <- list()
X$Y <- match(dat$year, years)
X$S <- match(dat$zone, zones)
X$C <- match(dat$country, countries)

# check numbers match
stopifnot(all(table(X$C) == table(dat$country)))

# check again
for (i in 1:nrow(dat)) {
    
    stopifnot(dat$country[i] == countries[X$C[i]])
    stopifnot(dat$zone[i]    == zones[X$S[i]])
}

# check
stopifnot(all.equal(dat$year, years[X$Y]))
stopifnot(all.equal(dat$zone, zones[X$S]))
stopifnot(all.equal(dat$country, countries[X$C]))

# make area sizes
areas <- merge(expand.grid(year = years, zone = zones), dat[, c('year', 'zone', 'survey_area')], all = TRUE)
areas <- reshape2::acast(areas, year~zone, fun.aggregate = function(x) mean(x, na.rm = TRUE), value.var = 'survey_area', fill = as.numeric(NA), drop = FALSE)

areas <- apply(areas, 2, redData::fill, complete = TRUE)

stopifnot(all(colnames(areas) == zones))

# get modal areas per zone
modal_areas <- data.frame(zone = dat$zone, modal_survey_area = dat$modal_survey_area)[!duplicated(data.frame(dat$zone, dat$modal_survey_area)),]
stopifnot(all(modal_areas$zone == zones))
stopifnot(nrow(modal_areas) == sum(S))

modal_areas$max_modal_survey_area <- numeric(sum(S))
for (i in 1:sum(S)) {
    modal_areas$max_modal_survey_area[i] <- max(as.numeric(unlist(strsplit(as.character(modal_areas[i,2]), ";"))))
}
```

```{r}
# save regression input data
savannah <- list(N = N, Y = Y, S = S, C = C, XY = X$Y, XC = X$C, XS = X$S,
                y = dat$density, 
                start = start,
                survey_area = t(areas), 
                range_area = modal_areas$max_modal_survey_area,
                use_relative_survey_area = FALSE)
                
save(savannah, dat, file = "../data/savannah.rda")
```


